-- ---------- DIM CATEGORIA (nivel "floco de neve" do produto) ----------
CREATE TABLE dw.dim_categoria (
    sk_categoria  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_pt  text UNIQUE,
    categoria_en  text
);

-- ---------- DIM PRODUTO (faz snowflake com dim_categoria) ----------
CREATE TABLE dw.dim_produto (
    sk_produto      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id      text UNIQUE NOT NULL,
    sk_categoria    bigint NOT NULL REFERENCES dw.dim_categoria (sk_categoria),
    peso_g          integer,
    comprimento_cm  integer,
    altura_cm       integer,
    largura_cm      integer,
    qtd_fotos       integer
);

-- ---------- DIM CLIENTE ----------
CREATE TABLE dw.dim_cliente (
    sk_cliente          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         text UNIQUE NOT NULL,
    customer_unique_id  text,
    cidade              text,
    estado              text,
    cep                 text
);

-- ---------- DIM VENDEDOR ----------
CREATE TABLE dw.dim_vendedor (
    sk_vendedor  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id    text UNIQUE NOT NULL,
    cidade       text,
    estado       text,
    cep          text
);

-- ---------- DIM PAGAMENTO ----------
CREATE TABLE dw.dim_pagamento (
    sk_pagamento          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_type          text,
    payment_installments  integer
);

-- ---------- DIM TEMPO (calendario) ----------
CREATE TABLE dw.dim_tempo (
    sk_tempo          integer PRIMARY KEY,   -- chave inteligente no formato AAAAMMDD
    data_completa     date,
    ano               integer,
    mes               integer,
    nome_mes          text,
    trimestre         integer,
    dia               integer,
    dia_semana        integer,               -- 1=segunda ... 7=domingo (ISO)
    nome_dia_semana   text,
    fim_de_semana     boolean
);

-- ---------- FATO VENDAS ----------
CREATE TABLE dw.fato_vendas (
    sk_fato          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Dimensoes DEGENERADAS (identificadores do pedido, sem dimensao propria)
    order_id         text NOT NULL,
    order_item_id    integer NOT NULL,
    order_status     text,

    -- Chaves estrangeiras (FK) -> dimensoes
    sk_cliente       bigint  REFERENCES dw.dim_cliente   (sk_cliente),
    sk_vendedor      bigint  REFERENCES dw.dim_vendedor  (sk_vendedor),
    sk_produto       bigint  REFERENCES dw.dim_produto   (sk_produto),
    sk_pagamento     bigint  REFERENCES dw.dim_pagamento (sk_pagamento),
    sk_data_compra   integer REFERENCES dw.dim_tempo     (sk_tempo),  -- role-playing 1
    sk_data_entrega  integer REFERENCES dw.dim_tempo     (sk_tempo),  -- role-playing 2

    -- Metricas (aditivas no grao do item)
    price            numeric(10,2),
    freight_value    numeric(10,2),
    dias_entrega     integer,

    CONSTRAINT uq_fato_item UNIQUE (order_id, order_item_id)
);

SELECT 'DDL do modelo estrela criado com sucesso.' AS status;